### ISSUE TITLE
brew update: Error Fetching 

### ISSUE THREAD

**Issue by duanemay** [spring-io/homebrew-tap#1]
If you have previously tapped this repo 

```
$ brew update
Error: Fetching /usr/local/Homebrew/Library/Taps/spring-io/homebrew-tap failed!
```

It appears the branch has changed from `master` to `main`

**Comment by wilkinsona** [comment]
Apologies for the inconvenience, @duanemay. Homebrew should [cope with this](https://github.com/Homebrew/brew/pull/10423) but doesn’t seem to do so unfortunately. Please run `brew tap --repair` to fix the problem.

We plan to tweet something from the Spring Boot Twitter account to let people know.
