### ISSUE TITLE
Support for installing 2.x spring-cloud-cli

### ISSUE THREAD

**Issue by BrianGilreath** [spring-io/homebrew-tap#5]
The spring-boot-cli 3.0.0 release had a major change. It no longer supports plugins and commands such as run and install. Some folks are going to want to continue using the 2.x version of the command (like myself)

Can we add versioned formulas? Here's an example - https://github.com/petere/homebrew-postgresql/blob/master/postgresql%4015.rb

**Comment by wilkinsona** [comment]
Can you please open a [Spring Boot issue](https://github.com/spring-projects/spring-boot/issues) for this request?
