### ISSUE TITLE
spring-boot.rb is not a Ruby file

### ISSUE THREAD

**Issue by gmercer** [spring-io/homebrew-tap#7]
Please see contents [https://github.com/spring-io/homebrew-tap/blob/main/spring-boot.rb](url), it looks more like a proxy fail error - an HTML file

**Comment by wilkinsona** [comment]
Thanks for reporting this, @gmercer. The problem should now be fixed. I've also opened https://github.com/spring-projects/spring-boot/issues/41561 to prevent it from happening again.
